apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-sample
  labels:
    app:  nginx-sample
spec:
  selector:
    matchLabels:
      app: nginx-sample
  replicas: 3
  template:
    metadata:
      labels:
        app:  nginx-sample
    spec:
      containers:
      - name:  nginx-sample
        image:  nginx:latest
        ports:
        - containerPort:  80
          name:  nginx-sample
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sample
  namespace: default
spec:
  selector:
    app: nginx-sample
  type: LoadBalancer
  ports:
  - name: nginx-sample
    protocol: TCP
    port: 80
    targetPort: 80