#@data/values
#@overlay/match-child-defaults missing_ok=True
---
infraProvider: vsphere
antrea:
  config:
    serviceCIDR: 100.64.0.0/13
    trafficEncapMode: encap
    noSNAT: false
    tlsCipherSuites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384
    disableUdpTunnelOffload: false
    featureGates:
      AntreaProxy: true
      EndpointSlice: false
      AntreaPolicy: true
      NodePortLocal: false
      AntreaTraceflow: true
      Egress: true
  image:
    repository: projects.registry.vmware.com/tkg
    path: antrea-advanced-debian
    tag: v1.2.3_vmware.4
    pullPolicy: IfNotPresent
