apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: hr-uat
spec:
  topology:
    controlPlane:
      count: 1
      class: best-effort-large
      storageClass: k8s-policy
      volumes:
        - name: etcd
          mountPath: /var/lib/etcd
          capacity:
            storage: 50Gi
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 50Gi
    workers:
      count: 2
      class: best-effort-large
      storageClass: k8s-policy
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 100Gi
  distribution:
    version: 1.21.6
  settings:
    storage: #optional storage settings
      classes: [ "k8s-policy" ]
      defaultClass: k8s-policy
    network:
      cni:
        name: antrea
      services:
        cidrBlocks: ["172.20.0.0/16"]
      pods:
        cidrBlocks: ["172.21.0.0/16"]
